### ISSUE TITLE
[BUG] SaucyBot posts pics from only one link when multiple links are posted in the same post 

### ISSUE THREAD

**Issue by MixHenry** [Sn0wCrack/saucybot-discord#15]
**Describe the bug**
When more than one link is posted by a user at the same time in one post, SaucyBot only pulls and uploads picture from one of those links.

**To Reproduce**
Paste at least two links in one message and send them. Those may be from the same or different sites.

**Expected behavior**
SaucyBot pulls and uploads images from every link posted.

**Additional context**
The original saucebot had that feature, therefore I figured I'd report it as a bug.
Issue was checked by posting double or mixed links from DeviantArt, FurAffinity and Pixiv
The bot seems to prioritize DeviantArt

**Comment by MixHenry** [comment]
Here's attachment with how it looks like in the Discord chat, For visibility, I deleted the Discord's embed after posting, since it would not fit my screen.

![attachment](https://user-images.githubusercontent.com/28789311/150653872-533b0050-5549-4c37-94d2-846883fb51a7.png)

**Comment by Sn0wCrack** [comment]
Hmm could have sworn this was the case at some point.

I'll take a look into it, should hopefully just be a matter of making a loop over all the results from the regex.

**Comment by Sn0wCrack** [comment]
Had some time this weekend and have made a branch with some very basic support on this. Going to clean up some UX stuff and maybe have it out in a week or so, with time and Elden Ring's release, permitting.
