### ISSUE TITLE
Twitter Image Reposts

### ISSUE THREAD

**Issue by RilsR** [Sn0wCrack/saucybot-discord#18]
Bot reposts twitter posts when the picture embed takes "too long" (half a second), resulting in multiple reposts. It also only posts a single image from a multi-image tweet.

**Comment by Sn0wCrack** [comment]
Currently deploying a fix for it not properly detecting if a message doesn't get an embed.

I essentially have it wait around half a second and then refetch the message to check if Discord has applied an embed.

Unfortunately as for multi-image tweets Discord only allows Bots to post single image embeds at the moment, I am able to post links to all the other images and have them embed, but I felt that wasn't the greatest looking thing.
