### ISSUE TITLE
FEEDBACK REQUESTED: Twitter NSFW Video and Twitter Failed Embeds Support

### ISSUE THREAD

**Issue by Sn0wCrack** [Sn0wCrack/saucybot-discord#19]
Now that I'm hoping I've got the bugs ironed out on that one.

I'd like to hear from people over the next couple of weeks as to what they think of this feature and how useful it seems to them.

I'm personally thinking of disabling this, but if enough people find this more useful than annoying, I'm more than willing to keep it enabled on the live version of SaucyBot.

Please let me know what you think in a reply here or by joining the [SaucyBot Support Discord Server](https://discord.gg/E642ScHyHj)

**Comment by NABU5309** [comment]
With Twitter starting to require login for viewing nsfw images. Images and videos might be needed with Saucybot as well

**Comment by Sn0wCrack** [comment]
> With Twitter starting to require login for viewing nsfw images. Images and videos might be needed with Saucybot as well
> 
> And maybe implement multiple images like is done for Pixiv?

Does Discord not embed these images? I've not noticed any issues when the embed is created successfully it still shows images from NSFW profiles and posts marked as NSFW.

**Comment by NABU5309** [comment]
Just tried and if I can view the image without logging on it will embed as usual but a number of tweets are now mentioning that you have to be logged in to see them (and those do not seem to be embedding into Discord).

**Comment by NABU5309** [comment]
Here are some examples
Will not embed (requires login);
https://twitter.com/doctorboda/status/1499072168801579014
Will embed (gives warning but you can click view without logging in);
https://twitter.com/BeingObscene/status/1492962309987188738?cxt=HHwWhICq3fLTiLgpAAAA

**Comment by Sn0wCrack** [comment]
Thanks for those examples.

Taking a look at it, Twitter's API doesn't really seem to return any data via their API to indicate why these display differently, both are marked as "possibly_sensitive."

I'll take a look ad adding multi-image embeds for Twitter on failed embeds, however, I do feel like that might make the false positives on this a bit more annoying when it's a multi-image post, but I'll see.

**Comment by NABU5309** [comment]
Seems like it is able to tell the difference which is good. Videos embed as well which is really good. 
I'm wondering if embedding multi-pics like with Pixiv is not an option down the road.

**Comment by Sn0wCrack** [comment]
Latest v1.7.20 now supports embedding multiple images in a single embed (no clue when Discord added this feature) as well as embedding both the video and original tweet if needed.

**Comment by NABU5309** [comment]
Hi, noticed that the mobile version of twitter does not embed while the regular version does .

https://mobile.twitter.com/Eye4Boobs/status/1247443055550042113 (this one does not work)
https://twitter.com/Eye4Boobs/status/1247443055550042113 (this one works)

**Comment by Sn0wCrack** [comment]
This should be fixed in v1.7.27.

I'm also going to close off this issue now, it looks like most people are fairly happy with the Twitter embed fixing, if there are any further issues just open up a new one and I'll have a look.
