### ISSUE TITLE
[BUG] Bot prioritizes videos of quote reply over content of the posted tweet on twitter

### ISSUE THREAD

**Issue by Kamil118** [Sn0wCrack/saucybot-discord#190]
**Describe the bug**
When bot tries to process a tweet that is a quote retweet reply to another post, if the replied to tweet includes a video, the bot will embed the quoted tweet instead of linked tweet media

**To Reproduce**
Example of tweet where the issue occurs (NSFW, not porn, but still nsfw): https://twitter.com/303_taroo/status/1763652002482188613

**Expected behavior**
Embeded media should be the images of the quote reply.

**Comment by Sn0wCrack** [comment]
I've been meaning to fix this up for a little while now.

Got a fix for it that I should have out soon.

**Comment by Sn0wCrack** [comment]
I've put the fix out for this now and appears to be working fine with your example.

I tested several other examples of this and it seems to be working well now.

Let me know if you have any further issues.
