### ISSUE TITLE
Furaffinity posts wont work.[BUG] 

### ISSUE THREAD

**Issue by Toaster98** [Sn0wCrack/saucybot-discord#21]
When posting links from Furaffinity the bot replies with 
"Matched link to FurAffinity, please wait..." 
But it gets stuck there and never posts the image. 

The issue has been present for over a week now. 
All other sites work as expected.

**Comment by MixHenry** [comment]
Can confirm, seems like there's a problem with connecting with FurAffinity. Perhaps something on their side got changed recently?

**Comment by NABU5309** [comment]
Can confirm as well, not working on a few servers.

**Comment by Sn0wCrack** [comment]
It looks like the bawk.space API for Furaffinity has gone down.

I'll take a look at implementing something else shortly.

**Comment by Sn0wCrack** [comment]
Fixed in release v1.7.17. Should also display some more info like the description, comments, views, etc.

Let me know if there's any further issues.
