### ISSUE TITLE
[NEW SITE] misskey.design

### ISSUE THREAD

**Issue by Yamakyu** [Sn0wCrack/saucybot-discord#222]
**Site Name**:  Misskey.design

**Site URL**: https://misskey.design/

**Example URLs**:
  * https://misskey.design/notes/9siwp6c225
  * https://misskey.design/notes/9pezpl4drg
  * https://misskey.design/notes/9n4j2ke1yg

From what I have seen, misskey.design URLs will embed properly on Discord if they contain one or multiple images, one or multiple animated GIFs, but not a **video**. This is what motivates this request.

As far as I know, misskey.design is based on Misskey, so I would assume at least some of the work for misskey.io support could prove useful for misskey.design.

**Comment by Sn0wCrack** [comment]
This has been implemented in v2.4.4.
