### ISSUE TITLE
[NEW SITE] Instagram

### ISSUE THREAD

**Issue by PhoenixInanis** [Sn0wCrack/saucybot-discord#23]
**Instagram**:  

**Site URL**: https://www.instagram.com/

**Example URLs**:
  * https://www.instagram.com/p/CTb1GMRMClX/
  * https://www.instagram.com/p/B-VlXGJlZXs/
  * https://www.instagram.com/p/CPQdD3HHRXY/

**Comment by Sn0wCrack** [comment]
Actually, I remember why I didn't continue with this more, it was that some stuff embeds and some stuff doesn't.

Since I have Twitter implemented this way I'll probably have it check for an embed or not. It also looks like videos don't embed properly so maybe I'll take a look at that.

**Comment by Sn0wCrack** [comment]
I've had another look into this today, and I don't believe this is easily possible.

I'm unsure how native Discord embeds for Instagram work and looking at the APIs available from Instagram to the general public, there is no easy way for me to create embeds of Instagram content that I would be satisfied with.

All known methods are either: deprecated, do not allow for accessing posts by ID, do not allow accessing all media on a post at one time, or do not allow accessing video posts.

For the time being, I'm going to close this feature request as it's impossible to achieve what is required with the resources I can find.

If anyone knows a good way to do all of the above, I'm more than happy to look into this future.
