### ISSUE TITLE
[Request] A config to disable Twitter video upload

### ISSUE THREAD

**Issue by Delphox** [Sn0wCrack/saucybot-discord#24]
Our server already uses [BDSMbed](https://github.com/Dastan21/BDSMbed) to link twitter video uploads directly so they play inline on mobile and web discord, and it makes no distinction between NSFW or not (since it doesn't matter for the library they use to fetch the video links). This in combination with Saucybot causes double uploads when the URL in question is detected as NSFW.

A setting to disable video uploads from the bot would be a simple way to work around this scenario.

**Comment by Sn0wCrack** [comment]
I do have plans in v2 to add settings to be able to disable embed sources and such on a per-server basis.

What you're probably seeing at the moment is that SaucyBot checks if it has permissions to send messages, create embeds or attach files in the channel it's attempting to reply in. If it doesn't, it will not attempt to create an embed in the first place and your message isn't even matched to a site.

The main reason I added this was I didn't want to process messages that wouldn't send in the first place, and secondly was to reduce errors I was seeing as discord.js throws up an error every time it receives a permission error on sending a message.

**Comment by Delphox** [comment]
I see, thanks for the response. Will be looking forward v2 then!
