### ISSUE TITLE
[BUG] Bot needs Manage Webhooks permission to respect Twitter embeds

### ISSUE THREAD

**Issue by arisinwonderland** [Sn0wCrack/saucybot-discord#242]
**Describe the bug**
Bot removes Twitter embeds after posting its own embed, but is only able to do so when Manage Webhooks is enabled for the bot.

**To Reproduce**
Disable "Manage Webhooks" for `@everyone` and leave it off for SaucyBot, then post a Twitter link.

**Expected behavior**
SaucyBot should request Manage Webhooks permissions when added to a server to prevent this issue. Ideally, if the permission was denied and Saucy is unable to delete an embed because of it, the bot should indicate somehow that it needs this permission to function properly. Even more ideally, the embed deletion feature should be toggleable.

**Additional context**
Image of example behavior. SaucyBot deletes the Twitter default embed if Manage Webhooks is on.
<img width="602" alt="Screen Shot 2024-06-01 at 6 16 49 PM" src="https://github.com/Sn0wCrack/saucybot-discord/assets/16226401/98cba07b-e4a9-4819-967c-e042f5f882d7">

**Comment by Sn0wCrack** [comment]
I'm unsure how Manage Webhooks is actually related to this issue.

From my understanding hiding the embed on another individuals post requires the "Manage Messages" permission, which the link on the repository here should include.

I've kicked and re-added the bot to a test server of mine and I can see it's removing the embeds on existing posts just fine.

Can you please check the SaucyBot role that gets assigned to the bot by default lists the following permissions as enabled and that no other roles are assigned to the bot that may disable them:

![Screenshot_20240602_095408](https://github.com/Sn0wCrack/saucybot-discord/assets/442287/0c7ffb9d-c0a5-482f-bc34-3a6c633e87fc)

**Comment by arisinwonderland** [comment]
While all the permissions listed were already on, I'm currently unable to reproduce the bug to take video of it despite having been able to do so yesterday. I'll reopen the ticket if this changes.
