### ISSUE TITLE
Saucybot doesn't embed Pixiv links [BUG] 

### ISSUE THREAD

**Issue by DarkTzitzimine** [Sn0wCrack/saucybot-discord#28]
Since yesterday Saucy isn't embedding Pixiv links, pasting the link gets the message that Saucybot is matching the links but then it doesn't do anything and only leaves the link as typed. Saucy works normally with Devianart, Twitter, Newgrounds, and Artstation. 

Oddly enough, I tried adding it to a dummy server I have to test bots and it works there perfectly, I tried matching the permissions between the two, and still doesn't work in my main server.

**Comment by Spoicrab** [comment]
Had the same problem, fixed when changing the server's name.

**Comment by DarkTzitzimine** [comment]
> Had the same problem, fixed when changing the server's name.

Wow, it worked. I would've never imagined that was the solution. Thank you so much for the advice.
