### ISSUE TITLE
[NEW SITE + BUG] SaucyBot removes misskey links

### ISSUE THREAD

**Issue by AoSankaku** [Sn0wCrack/saucybot-discord#328]
**Site Name**:  Misskey(Mastodon-like decentralized social network)

**Site URL**: 
- https://misskey.io
- https://mi.nakn.jp
- <Link deducted for safety>

**Comment by Sn0wCrack** [comment]
Could you please elaborate on this issue?

The Misskey integration only works for misskey.io and misskey.design and only embeds image posts that have more than 1 image or is NSFW.

**Comment by AoSankaku** [comment]
I've been trying to reproduce the bug that saucybot just removes the vanilla embed, but this may be possibly caused by other bot. Sorry for misinformation, and I'll close this issue as not planned.

(I still think it'll be great to support any other misskey servers embedding ;-))
