### ISSUE TITLE
How to configure for Pixiv links

### ISSUE THREAD

**Issue by BBandit18** [Sn0wCrack/saucybot-discord#33]
I'm trying to change the limit for pixiv image on my server but can't seem to find it

**Comment by BBandit18** [comment]
Okay that doesn't really help, I should've been more specific, how do I change the limit on discord, like what commands can I use

**Comment by LeviSnoot** [comment]
The bot doesn't have per-server settings yet, the only way to change these settings is by hosting the bot yourself.

**Comment by BBandit18** [comment]
And how do I do that

**Comment by Sn0wCrack** [comment]
The current publicly hosted version of SaucyBot does not support changing the number of images Pixiv posts on a per-server basis.

I have plans to add this to version 2.0 of SaucyBot that I'm currently working on, however there will still be a cap for the amount of images Pixiv can post that users are able to set.

The reason a cap needs to exist is that in order for SaucyBot to process a Pixiv link it needs to download all the images from Pixiv and then upload them to Discord, thus using extra CPU, RAM and bandwidth per image it processes and thus tying up resources it could be using to post less intensive embeds and also incurring further costs to me for the hosting of the public version of the bot.

**Comment by BBandit18** [comment]
ok then

**Comment by LeviSnoot** [comment]
> And how do I do that 

> And how do I do that 

I think @Sn0wCrack's reply is sufficient but if you have command line skills you can install git and docker and host the bot using the instructions provided in my PR #32.

**Comment by BBandit18** [comment]
I don't have those skills at all

**Comment by LeviSnoot** [comment]
In that case you're best off waiting for v2 to come out :)
