### ISSUE TITLE
[BUG] Bluesky posts don't embed images when it's a quote-post with an image

### ISSUE THREAD

**Issue by BenneyR** [Sn0wCrack/saucybot-discord#337]
**Describe the bug**
When the post is being embedded by SaucyBot, it retrieves the information correctly but it doesn't embed the image connected to the post. The issue seems to be happening when the post is a quote-post where both posts are using an image.

It does try to embed the image for a second, but it seems to delete it immediately after posting the information embed.

**To Reproduce**
Have a post on Bluesky that is an image, quote-post that post with an image as well, then post the quote-post Bluesky link into Discord.

**Expected behavior**
It should be embedding the image from the quote-post, while also not embedding the image of the post it is quoting.

**Additional context**
Maybe a new form of embedding for Bluesky posts is needed for Discord, like with Twitter and the VX embedding.

**Comment by Sn0wCrack** [comment]
The BlueSky stuff right now is a little beta so it's not fully feature complete.

Looking at how BlueSky does this, it's kind of annoying to implement compared to Twitter so probably not super high on my TODO list, but I've added the variables and typings for this so I can at least look at the data.

**Comment by Sn0wCrack** [comment]
This should be fixed now in the latest release.
