### ISSUE TITLE
[BUG] Twitter embeds remain unreliable - consider always replacing

### ISSUE THREAD

**Issue by noideas4thisname** [Sn0wCrack/saucybot-discord#34]
**Describe the bug**
This is more of a feature ask - but I wanted to start a discussion on if there's a way to make fixing twitter embeds more reliable. Right now if I'm looking at the check right, it seems it only replaces the embed if Discord failed to create one. Can we have an option for it to fix them in all instances so it achieves fixing broken Twitter embeds like vxtwitter, twxtter, or other similiar parent services?

**To Reproduce**
Any twitter link with a video. The embed may be successful in discord, but the video frequently fails to play from the twitter embed.

**Expected behavior**
An embedded video is created that can reliably be played in Discord.

**Additional context**
Open to other suggestions - I was just hoping this remained a reliable way to automatically convert twitter links to ones that played correctly in discord embeds.

**Comment by Sn0wCrack** [comment]
With SaucyBot v1 I try to remain as unobtrusive as possible and only fix embeds when I can guarantee they need fixing.

Right now the logic is:

- If no embed is made, create embed.
- If an embed is made, but the embed is malformed, create embed.
- If an embed is made, has a video attached to it, and is marked as NSFW, create embed and upload video.

I'm still plodding along in what free time with SaucyBot v2, where a customization option for this could be made available.

One thing to keep in mind is embedding the video does incur additional additional bandwidth, disk and memory usage, however there may be workarounds to this by simply providing the link in the message, etc.

**Comment by noideas4thisname** [comment]
Makes sense - thanks for at least considering it. If v2 manages to serve this purpose I'll keep an eye out for that if it feels needed. I wish Twitter would just fix it on their end but that's certainly not going to happen any time soon.
