### ISSUE TITLE
FurAffinity descriptions are given many excess blank lines.

### ISSUE THREAD

**Issue by coredumperror** [Sn0wCrack/saucybot-discord#42]
**Describe the bug**
When SaucyBot creates an embed for a FurAffinity post, it adds an extra blank line between every line in the description.

**To Reproduce**
Paste this into a Discord message: https://www.furaffinity.net/view/51719696/

**Expected behavior**
The description should look like what fxfurafinity embeds:
<img width="448" alt="fxFA" src="https://user-images.githubusercontent.com/413571/231607847-65fc7d3c-d327-4126-8524-b349d2f05fca.png">

Instead, it looks like this:
<img width="519" alt="SaucyFA" src="https://user-images.githubusercontent.com/413571/231607876-f95bd135-4040-42e5-a57d-2b384e1c6cb4.png">

**Additional context**
It looks like the parser is just accidentally adding a blank line after every single line in the original description. Should be a fairly simple fix.

**Comment by Sn0wCrack** [comment]
This should now be fixed.

**Comment by coredumperror** [comment]
Killer! Thanks.
