### ISSUE TITLE
[NEW SITE] Any chance we can get the bot to recognize Nitter links as well and treat similarly to Twitter?

### ISSUE THREAD

**Issue by noideas4thisname** [Sn0wCrack/saucybot-discord#43]
**Site Name**:  Nitter

**Site URL**: https://nitter.net/

**Example URLs**:
  * [Example 1](https://nitter.net/weirdlilguys/status/1671550316062408706)
  * [Example 2](https://nitter.net/CatWorkers/status/1671568420406427666#m)
  * [Example 3](https://nitter.net/ShouldHaveCat/status/1671535086800437249#m)
  
 Nitter links don't seem to embed in discord so this could be a nice addition.

**Comment by Sn0wCrack** [comment]
Better late than never but Nitter will now get matched the same way Twitter and X do.

**Comment by axiopaladin** [comment]
There are a few other sites that serve the nitter client, maybe they should be added to the list too? There's an "official" [list of public instances](https://github.com/zedeus/nitter/wiki/Instances) over on the nitter github wiki, but currently it's really just these:
 - [xcancel.com](https://xcancel.com/)
 - [nitter.poast.org](https://nitter.poast.org/)
 - [nitter.privacyredirect.com](https://nitter.privacyredirect.com/)
 - [lightbrd.com](https://lightbrd.com/)
