### ISSUE TITLE
[BUG] Twitter video embed

### ISSUE THREAD

**Issue by Baramanga** [Sn0wCrack/saucybot-discord#51]
So Saucy bot stopped download and embed Twitter videos to server because of Twitter god awful API. have u been able to work around this yet? 🥺

**Comment by Sn0wCrack** [comment]
Yeah this is related to Twitter's API changes.

I'm currently using the new FixTweet API, which did work for a while before more API changes occurred.

You can follow the issue at FixTweet here: https://github.com/FixTweet/FixTweet/issues/333

Unfortunately not much I can do about working around this without joining in the effort to circumvent Twitter's API.

I may potentially disable the Twitter embeds on the production SaucyBot until another workaround has been found.

**Comment by Baramanga** [comment]
> Yeah this is related to Twitter's API changes.
> 
> I'm currently using the new FixTweet API, which did work for a while before more API changes occurred.
> 
> You can follow the issue at FixTweet here: [FixTweet/FixTweet#333](https://github.com/FixTweet/FixTweet/issues/333)
> 
> Unfortunately not much I can do about working around this without joining in the effort to circumvent Twitter's API.
> 
> I may potentially disable the Twitter embeds on the production SaucyBot until another workaround has been found.

Can you use vxtwitter instead?

**Comment by Sn0wCrack** [comment]
> Can you use vxtwitter instead?

For some reason I was under the impression that vxtwitter did not have an API, but it looks like they do.
I can take a look to see if it does what I need for SaucyBot.

**Comment by Sn0wCrack** [comment]
I believe fxtwitter has resolved the majority of issues from what I can see and if the recent wave of the "site formerly known as Twitter" not embedding has shown anything, it's that SaucyBot has been embedding posts pretty decently now.

I have noticed a few posts not embed correctly, which I'll attempt to investigate, but I think it's going to be a timing issue rather than something fixable.

**Comment by Sn0wCrack** [comment]
I've tracked down the issue primarily to be related to Twitter/X having its own issues, in my replication when images and posts fail to load correctly on the app, FxTwitter fails to work.

I'm pretty much going to close this issue now as I've resolved as much as I can on my end.
