### ISSUE TITLE
[BUG] twitter changing to x.com so embed fix no longer works

### ISSUE THREAD

**Issue by mooosees** [Sn0wCrack/saucybot-discord#57]
twitter is switching their links to x.com. can the bot fix the embeds for x the same way it has for twitter? the vx creator has made fixv to work with x so it should all work the same way. aka

twitter.com -> vxtwitter.com
x.com -> fixvx.com

**Comment by Sn0wCrack** [comment]
This should hopefully be a one line code fix on my end, so I'll look at doing this tonight.

**Comment by Sn0wCrack** [comment]
x.com should now get embedded the same way twitter.com links do.
