### ISSUE TITLE
Feature Request: Allow users to delete bot embeds to their links

### ISSUE THREAD

**Issue by Aradeid** [Sn0wCrack/saucybot-discord#65]
At rare occasions the link will be embedded properly, but the bot will still add a second embed, pretty much duplicating the message.
At other situations, the user specifically posts a link not wanting it to embed (for example nsfw content in a safe channel), but there is no way to stop the bot from embedding.
More commonly a user will post a link in the wrong channel, and even if they delete their message, the embed will remain.
In situations like this, only a mod can delete the mistake and mods are simply not always available.

There needs to be a way for all users to delete embeds of their own links. A suggestion is to use a specific reaction emote (for example ❌) that instructs the bot to delete the message if it's triggered by the message author.

**Comment by Sn0wCrack** [comment]
The original embed should always get suppressed by SaucyBot so long as it has the "Manage Messages" permissions within the channel the original link is posted in.

If you don't want SaucyBot to post an embed in a specific channel you can remove its permissions to view and/or post messages within that channel using Discord's permission system.

If you don't want SaucyBot to look at a link in a specific instance of the link, placing the link inside of a "<" and ">" (example: `<https://twitter.com/randomsakuga/status/1699724195628982465?s=20>`) will prevent SaucyBot from looking at the link.
